#!/usr/bin/env bash

GIT_ROOT=`git rev-parse --show-toplevel`
REFORMALITY_ROOT=$GIT_ROOT/../re-formality

cd $GIT_ROOT
./scripts/clean

# Build
cd $REFORMALITY_ROOT
yarn install
cd lib
esy install
esy build
yarn bs:build
yarn bs:install
esy x test.exe

# package binary
cd $REFORMALITY_ROOT
mkdir -p _release/bin
cp lib/_build/default/bin/bin.exe _release/bin/re-formality-ppx-darwin-arm64.exe

# package lib
cd $REFORMALITY_ROOT
mkdir -p _release/src
cp README.md _release/README.md
cp lib/bsconfig.json _release/bsconfig.json
cp -a lib/src/. _release/src/
cp .github/workflows/scripts/postinstall.js _release/postinstall.js
node .github/workflows/scripts/write-package-json.js
sed -i '' 's/x64/arm64/' _release/postinstall.js

# copy package to temporary repo
cd $GIT_ROOT
cp -a $REFORMALITY_ROOT/_release/* ./

