// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Id from "bs-platform/lib/es6/belt_Id.mjs";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.mjs";
import * as FormalityCompat__FormAsyncOnChangeWithId from "./FormalityCompat__FormAsyncOnChangeWithId.bs.js";

function Make(Form) {
  var cmp = Caml_obj.caml_compare;
  var FieldId = Belt_Id.MakeComparable({
        cmp: cmp
      });
  return FormalityCompat__FormAsyncOnChangeWithId.Make({
              debounceInterval: Form.debounceInterval,
              validators: Form.validators,
              FieldId: FieldId
            });
}

var Validation;

var defaultDebounceInterval = FormalityCompat__FormAsyncOnChangeWithId.defaultDebounceInterval;

export {
  Validation ,
  defaultDebounceInterval ,
  Make ,
  
}
/* FormalityCompat__FormAsyncOnChangeWithId Not a pure module */
