// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FormalityCompat__PublicHelpers from "./FormalityCompat__PublicHelpers.bs.js";
import * as FormalityCompat__FormAsyncOnChangeWithId from "./FormalityCompat__FormAsyncOnChangeWithId.bs.js";

var Async = {
  Make: undefined,
  MakeWithId: undefined,
  MakeOnBlur: undefined,
  MakeOnBlurWithId: undefined,
  debounceInterval: FormalityCompat__FormAsyncOnChangeWithId.defaultDebounceInterval
};

var Dom = FormalityCompat__PublicHelpers.Dom;

var Strategy;

var FormStatus;

var Make;

var MakeWithId;

export {
  Dom ,
  Strategy ,
  FormStatus ,
  Make ,
  MakeWithId ,
  Async ,
  
}
/* FormalityCompat__FormAsyncOnChangeWithId Not a pure module */
