// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.mjs";
import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.mjs";

function useReducer(initialState, reducer) {
  var match = React.useReducer((function (fullState, action) {
          var state = Curry._2(reducer, fullState.state, action);
          if (typeof state === "number") {
            return fullState;
          } else if (state.TAG === /* Update */0) {
            return {
                    state: state._0,
                    sideEffects: fullState.sideEffects
                  };
          } else {
            return {
                    state: state._0,
                    sideEffects: {
                      contents: Belt_Array.concat(fullState.sideEffects.contents, [state._1])
                    }
                  };
          }
        }), {
        state: initialState,
        sideEffects: {
          contents: []
        }
      });
  var dispatch = match[1];
  var match$1 = match[0];
  var sideEffects = match$1.sideEffects;
  var state = match$1.state;
  React.useEffect((function () {
          if (sideEffects.contents.length !== 0) {
            Belt_Array.forEach(sideEffects.contents, (function (fn) {
                    return Curry._1(fn, {
                                state: state,
                                dispatch: dispatch
                              });
                  }));
            sideEffects.contents = [];
          }
          
        }), [sideEffects.contents]);
  return [
          state,
          dispatch
        ];
}

export {
  useReducer ,
  
}
/* react Not a pure module */
