// Generated by ReScript, PLEASE EDIT WITH CARE


var Result = {};

var Visibility = {};

var Sync = {};

var Async = {};

var Startegy;

export {
  Startegy ,
  Result ,
  Visibility ,
  Sync ,
  Async ,
  
}
/* No side effect */
