// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Debouncer from "re-debouncer/src/Debouncer.bs.js";

var make = Debouncer.make;

var makeCancelable = Debouncer.makeCancelable;

export {
  make ,
  makeCancelable ,
  
}
/* No side effect */
